name: CD · Tag & Release
run-name: "CD · ${{ github.event_name }} · ${{ github.sha }}"

on:
  push:
    branches: [main]
    paths-ignore:
      - ".github/self-*.yml"

concurrency:
  group: "release-${{ github.ref }}"
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  init:
    if: ${{ !cancelled() }}
    permissions:
      contents: read
      actions: read
      pull-requests: read
    uses: ./.github/workflows/init.yml
    secrets: inherit
    with:
      ignore-docker: ${{ 'true' }}
      ignore-chart: ${{ 'true' }}

  release:
    needs: init
    permissions:
      contents: write
      actions: read
    uses: ./.github/workflows/release.yml
    secrets: inherit
    with:
      tag: ${{ needs.init.outputs.tag }}
      upstream-run-id: ${{ needs.init.outputs.upstream-run-id }}
      notify: true
