name: Security · Library Git Secrets
run-name: "Security · ${{ github.event_name }} · ${{ github.sha }}"

on:
  workflow_dispatch:
    inputs:
      full-history:
        description: Scan the entire history rather than the pull request range
        required: false
        default: true
        type: boolean
  workflow_call:
    inputs:
      full-history:
        required: false
        default: false
        type: boolean

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  secret-scan:
    name: Secret Scan
    uses: ./.github/workflows/secret-scanning.yml
    secrets: inherit
    with:
      full-history: ${{ inputs.full-history }}
